# Generated by Django 2.2 on 2019-04-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summart',
            new_name='summary',
        ),
    ]
